var name_template = @include('core.forms.templates.common.name')
var email_template = @include('core.forms.templates.common.email')
var message_template = @include('core.forms.templates.common.message')
var address_template = @include('core.forms.templates.common.address')
var city_template = @include('core.forms.templates.common.city')
var zipcode_template = @include('core.forms.templates.common.zipcode')
var state_template = @include('core.forms.templates.common.state')
var country_template = @include('core.forms.templates.common.country')
var phone_template = @include('core.forms.templates.common.phone')
var website_template = @include('core.forms.templates.common.website')

var text_template = @include('core.forms.templates.basic.text')
var textarea_template = @include('core.forms.templates.basic.textarea')
var checkbox_template = @include('core.forms.templates.basic.checkbox')
var select_template = @include('core.forms.templates.basic.select')
