
<div class="box box-primary">
    <div class="box-header with-border">
        <h3 class="box-title">{{ $title }}</h3>
        @if($mode == 'edit')
            <div class="pull-right"><a href="{{ $viewurl }}" target="_blank" class="btn btn-block btn-default btn-sm">View {{$type}}</a></div>
        @endif
    </div>
    <div class="box-body">
        <div class="form-group title-group">
            <label for="title">Title</label>
            @if($mode == 'edit')
                <input type="hidden" value="{{ $content->id }}" id="id" class="form-control">
                <input type="text" placeholder="Enter title" value="{{ $content->title }}" id="title" name="title" class="form-control">
            @else
                <input type="text" placeholder="Enter title" id="title" name="title" class="form-control">
            @endif

            <span class="help-block">
                <small class="title-feedback"></small>
            </span>
        </div>

        <div class="form-group">
            <label for="slug">Slug</label>
            @if($mode == 'edit')
                <input type="text" id="slug" placeholder="Autogenerated if empty" value="{{ $content->slug }}" class="form-control">
            @else
                <input type="text" id="slug" placeholder="Autogenerated if empty" class="form-control">
            @endif
        </div>

        <div class="form-group" @if(!$show_categories) style="display: none;" @endif>
            <label for="categories">Categories</label>
            <select id="categories" multiple="multiple" class="form-control js-states " name="categories[]">
                @if(isset($categories))
                    @foreach ($categories as $category)
                        <option value="{{ $category->id }}">{{ $category->title }}</option>
                    @endforeach
                @endif
            </select>
        </div>

        <div class="form-group" @if(!$show_tags) style="display: none;" @endif>
            <label for="tags">Tags</label>
            <select id="tags" multiple="multiple" class="form-control js-states" name="tags[]">
                @if(isset($tags))
                    @foreach ($tags as $tag)
                        <option value="{{ $tag->id }}">{{ $tag->title }}</option>
                    @endforeach
                @endif
            </select>
        </div>

        @if(isset($tabcontent))
            {{ $tabcontent }}
        @endif

    </div>
</div>

@push('scripts')
    {{-- <script src="https://cdn.ckeditor.com/4.5.7/standard/ckeditor.js"></script> --}}
    {{-- <script src="http://cdn.ckeditor.com/4.6.1/standard-all/ckeditor.js"></script> --}}
    <script src="{{asset('js/init_simplemde.js')}}"></script>
    <script src="{{asset('js/publishable.js')}}?{{ str_random(7) }}"></script>
    <script src="{{ asset('js/contentblocks.js') }}?{{ str_random(7) }}"></script>

    <script>
        // var config = {
        //     extraPlugins: 'image2',
        //     height: 280,
        //     allowedContent: true
        // };
        // var post = CKEDITOR.replace( 'postBody', config );
        // $('#publish_date').datetimepicker()

        publishable.data.publish = {{ Content::PUBLISH }}
        publishable.data.draft = {{ Content::DRAFT }}
        publishable.data.schedule = {{ Content::SCHEDULE }}

        @if($mode == 'edit')
            publishable.data.status.publish_text = @if($content->status == Content::PUBLISH) 'Published' @else()'Publish'@endif
        @elseif($mode == 'create')
            publishable.data.status.publish_text = 'Publish'
        @endif

        publishable.data.status.draft_text = 'Draft'
        publishable.data.status.schedule_text = 'Scheduled'

        publishable.data.access.everyone = {{ Content::EVERYONE }}
        publishable.data.access.members = {{ Content::MEMBERS }}
        publishable.data.access.subscribers = {{ Content::PREMIUM_MEMBERS }}

        publishable.data.access.everyone_text = 'Everyone'
        publishable.data.access.members_text = 'Members'
        publishable.data.access.subscribers_text = 'Premium Members'

        @if($mode == 'edit')
            publishable.data.picked_status = {{ $content->status}}
            publishable.data.picked_access = {{ $content->access}}
        @endif

        publishable.init()

        var simplemde = null
        simplemde = initSimpleMde("content_editor")

        $("#saveBtn").on("click", function(e) {
            var saveBtn = $(this)

            disableBtn(saveBtn, 'Saving')

            var content = null

            if(simplemde) {
                content = simplemde.value()
            }

            var selectedCategories = []
            $("#categories :selected").each(function() {
                selectedCategories.push($(this).val())
            })

            var selectedTags = []
            $("#tags :selected").each(function() {
                selectedTags.push($(this).val())
            })

            var settings = []
            @if(isset($settings))
                {{ $settings }}
            @endif

            $.ajax('{{ $saveurl }}', {
                method: 'POST',
                dataType:'json',
                data: {
                    id: $('#id').val(),
                    title: $('#title').val(),
                    slug: $('#slug').val(),
                    content: content,
                    categories: selectedCategories,
                    tags: selectedTags,
                    password: $('#password').val(),
                    status: publishable.data.picked_status,
                    access: publishable.data.picked_access,
                    settings: JSON.stringify(settings),
                    published_at: publishable.data.publish_date,
                    _token: Laravel.csrfToken
                },

                success: function(result) {
                    @if($mode == 'create')
                        var redirectTo = "{{ $editurl }}";
                        redirectTo = redirectTo.replace('0', result.content.id);
                        window.location.href = redirectTo;
                    @endif

                    enableBtn(saveBtn, 'Save')

                    $('.content').find('.title-group').removeClass('has-error')
                    $('.content').find('.title-feedback').html('')

                    $('#updated_at').text(result.content.updated_at)
                    $('#slug').val(result.content.slug)

                    feedback("Successfully updated.", "callout-info", 4000)

                    // var selectCat = ''
                    // var postCats = []
                    // $.each(result.categories, function( key, post ) {
                    //     selectCat += '<option value="'+post.id+'">'+post.title+'</option>'
                    // })
                    // $("categories").select2("destroy")
                    // $('#categories').empty()
                    // $('#categories').append(selectCat)
                    // $.each(result.post.categories, function( key, category ) {
                    //     postCats.push(category.id)
                    // })
                    // $('#categories').select2().val( postCats ).trigger('change')
                    // $('#categories').select2({tags: true, placeholder: 'Select Categories...', width: '100%'})
                    //
                    // var selectTag = ''
                    // var postTags = []
                    // $.each(result.tags, function( key, post ) {
                    //     selectTag += '<option value="'+post.id+'">'+post.title+'</option>'
                    // });
                    // $("tags").select2("destroy")
                    // $('#tags').empty()
                    // $('#tags').append(selectTag)
                    // $.each(result.post.tags, function( key, tag ) {
                    //     postTags.push(tag.id)
                    // });
                    // $('#tags').select2().val( postTags ).trigger('change')
                    // $('#tags').select2({tags: true, placeholder: 'Select Tags...', width: '100%'})

                    if(result.content.status == {{ Content::DRAFT }}) {
                        publishable.data.status.publish_text = 'Publish'
                    }
                    else if(result.content.status == {{ Content::PUBLISH }}) {
                        publishable.data.status.publish_text = 'Published'
                    }

                },
                error: function(result) {
                    enableBtn(saveBtn, 'Save');
                    var errors = result.responseJSON;

                    if(errors) {
                        $('.content').find('.title-group').removeClass('has-error');
                        $('.content').find('.title-feedback').html('');

                        if(typeof errors.title !== 'undefined'){
                            $('.content').find('.title-group').addClass('has-error');
                            $('.content').find('.title-feedback').html(errors.title);
                        }
                    } else {
                        feedback("Can't save the content for some reason.", "callout-danger", 5000);
                    }
                }
            });
        });
    </script>
@endpush
