<template>
    <div class="row">
        <div :class="(this.wideLayout == true) ? 'col-md-12' : 'col-md-9'">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">{{modeText}}</h3>
                    <button v-if="this.minimalLayout && this.wideLayout" @click="saveBtn()" :disabled='saveBlocks' style="width: 70px; padding: 2px 12px;" class="btn btn-primary pull-right" type="submit">{{saveBtnText}}</button>
                </div>

                <div class="box-body">
                    <div class="form-group" v-if="this.wideLayout && !this.minimalLayout">
                        <div class="form-group pull-right" style="margin-bottom: 5px;">
                            <button @click="saveBtn()" :disabled='saveBlocks' style="width: 70px;" class="btn btn-primary" type="submit">{{saveBtnText}}</button>
                        </div>
                        <div v-if="editorMode=='edit'" class="form-group">
                            <div class="mydiv">
                                <label>Author:</label>
                                <div>Author name here</div>
                            </div>

                            <div class="mydiv">
                                <label>Status:</label>
                                <div>
                                    <span @click="cycleStatus" class="label label-info" style="cursor: pointer; font-size: 14px;">{{statusText}}</span>
                                </div>
                            </div>

                            <div class="mydiv">
                                <label>Date:</label>
                                <div v-if="status == 1 || status == 2" style="font-weight: bold;">{{dateText}}</div>
                                <div v-show="status == 3">
                                    <el-date-picker
                                        v-model="dateTimePicker"
                                        format="yyyy-MM-dd HH:mm"
                                        type="datetime"
                                        size='small'
                                        placeholder="Pick a date">
                                    </el-date-picker>
                                </div>
                            </div>
                        </div>
                        <div style="clear: both;"></div>
                    </div>
                    <div style="clear: both;"></div>

                    <div class="form-group">
                        <label style="margin-right: 5px;">Title</label>
                        <input class="form-control" v-model="contentTitle"
                            v-validate="'required'"
                            :class="{'form-control':true, 'input': true, 'is-danger': errors.has('title') }"
                            name="title"
                            type="text"
                            placeholder="Enter Title">
                        <span v-show="errors.has('title')" class="help is-danger">{{ errors.first('title') }}</span>
                    </div>

                    <div v-show="displayContentSlug" class="form-group">
                        <label>Slug</label>
                        <input class="form-control" v-model="slug" type="text" placeholder="Autogenerated">
                    </div>

                    <div id="blocks">
                        <draggable
                            :move="onMove"
                            @end="onEnd"
                            v-model="containerList"
                            :options="{handle:'.fa-arrows', chosenClass:'dragging1'}">
                            <component v-for="container in containerList"
                                v-bind:is="container.type"
                                :uniqueId="container.uniqueId"
                                v-bind="container.settings"
                                :show-headers="showHeaders"
                                :show-content="showContent"
                                v-on:remove="removeContainer(container.uniqueId)"
                                :key="container.uniqueId">
                            </component>
                        </draggable>
                    </div>

                    <div id="buttons">
                        <button v-on:click="addContainer('ContainerBlock')" type="button" name="button" class="btn btn-primary btn-sm">Add Container</button>
                    </div>
                </div>
            </div>
        </div>

        <div v-if="!wideLayout" class="col-md-3">
            <div class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Save Options</h3>
                    <i class="fa fa-info-circle pull-right" style="cursor: pointer;" aria-hidden="true"></i>
                </div>

                <div class="box-body">
                    <div class="form-group sidebar">
                        <table class="table noselect">
                            <tbody>
                                <tr v-if="editorMode=='edit'">
                                    <td style="width: 75px;">Author:</td>
                                    <td>
                                        <span><b>Author</b></span>
                                    </td>
                                </tr>
                                <tr>
                                    <td style="width: 75px;">Status:</td>
                                    <td>
                                        <span @click="cycleStatus" class="label label-info" style="cursor: pointer; font-size: 14px;">{{statusText}}</span>
                                    </td>
                                </tr>

                                <tr>
                                    <td style="vertical-align: middle;">Date:</td>
                                    <td>
                                        <span v-if="status == 1 || status == 2" style="font-weight: bold;">{{dateText}}</span>
                                        <span v-show="status == 3">
                                            <el-date-picker
                                                v-model="dateTimePicker"
                                                format="yyyy-MM-dd HH:mm"
                                                type="datetime"
                                                size='small'
                                                placeholder="Pick a date">
                                            </el-date-picker>
                                        </span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

                <div class="box-footer">
                    <button @click="saveBtn()" :disabled='saveBlocks' style="width: 70px;" class="btn btn-primary pull-right" type="submit">{{saveBtnText}}</button>
                </div>
            </div>

            <div v-if="editorMode=='edit'" class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Featured Image</h3>
                </div>

                <div class="box-body">
                    <div class="form-group sidebar">
                        <div v-if="!contentData.featuredImage" @click="openMediaModal" class="set-featured-image">
                            Set Featured Image
                        </div>
                        <div v-else>
                            <div @click="openMediaModal" class="featured-image">
                                <img :src="contentData.featuredImage.medium" class="img-responsive">
                            </div>
                            <div @click="removeFeaturedImage" class="text-center remove-featured-image">
                                Remove Featured Image
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div v-if="editorMode=='edit'" class="box box-primary">
                <div class="box-header with-border">
                    <h3 class="box-title">Content Info</h3>
                </div>

                <div class="box-body">
                    <div class="form-group sidebar">
                        <table class="table noselect">
                            <tbody>
                                <tr>
                                    <td>Created:</td>
                                    <td>
                                        <span>
                                           <b><span>{{ contentData.createdAt }}</span></b>
                                        </span>
                                    </td>
                                </tr>
                                <tr>
                                    <td>Updated:</td>
                                    <td>
                                        <span>
                                           <b><span>{{ contentData.updatedAt }}</span></b>
                                        </span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <content-blocks-popup></content-blocks-popup>
    </div>
</template>
<script>
    import { mapGetters, mapActions } from 'vuex'
    import { processSettings, processSettingsConfig, getComponentByName } from 'utils/helpers.js'
    import draggable from 'vuedraggable'
    import Modal from 'components/ui/Modal.vue'
    import ContentBlocksPopup from 'components/ui/ContentBlocksPopup.vue'

    export default {
        components: {
            Modal,
            ContentBlocksPopup,
            draggable
        },
        data: function data() {
            return {
                contentTitle: this.initContentTitle,
                slug: this.initSlug,
                displayContentSlug: this.initDisplayContentSlug,
                wideLayout: this.initWideLayout,
                minimalLayout: this.initMinimalLayout,
                contentType: this.initContentType,
                contentId: this.initContentId,

                status: this.initContentStatus,
                dbStatus: this.initContentStatus,
                dateTimePicker: this.localDateTime(this.initPublishedAtDate),
                publishedAtDate: this.localDateTime(this.initPublishedAtDate),
                createdAtDate: this.localDateTime(this.initCreatedAtDate),
                updatedAtDate: this.localDateTime(this.initUpdatedAtDate),
                saveBlocks: false,
                saved: this.initSaved,
                passwordSupport: this.initFeatureEnablePasswordSupport,
                accessControl: this.initFeatureEnableAccessControl,
                featuredImageEnabled: this.initFeatureEnableFeaturedImage,
                scheduledAtDate: null,
                showHeaders: true,
                showContent: true,
                featuredImage: null,
            }
        },
        props: {
            initContentStatus: {type: Number, default: 1},
            initWideLayout: {type: Boolean, default: false},
            initMinimalLayout: {type: Boolean, default: false},
            content: {type: Object, default: null},
            initTitle: {type: String, default: ''},
            initSlug: {type: String, defaul: ''},
            initContentTypeId: {type: Number, default: 0},
            initDisplayContentSlug: {type: Boolean, defaul: false},
            initEditorMode: {type: String, default: 'create'},
            initSaved: {type: Boolean, default: false},
            initContentId: {type: Number, default: 0},
            initContentTitle: {type: String, default: ''},
            initContentType: {type: String, default: null},
            initPublishedAtDate: {type: String, default: null},
            initCreatedAtDate: {type: String, default: null},
            initUpdatedAtDate: {type: String, default: null},
            initFeatureEnablePasswordSupport: {type: Boolean, default: false},
            initFeatureEnableAccessControl: {type: Boolean, default: true},
            initFeatureEnableFeaturedImage: {type: Boolean, default: true},
            initEditPageShowAuthor: {type: Boolean, default: true},
            initEditPageShowContentInfo: {type: Boolean, default: true},
        },
        watch: {
            contentTitle(val, old) {
                let payload = {
                    contentTitle: val,
                }
                this.setContentData(payload)
            },
            dateTimePicker(val, old) {
                this.publishAt = val
            },
            statusMode(val) {
                if(val == 'publish')
                    this.publishAt =  null
                else if(val == 'draft')
                    this.publishAt = null
                else if(val == 'schedule')
                    this.publishAt = this.dateTimePicker

                if(val == 'published')
                    this.publishAt = this.publishedAt
                else if(val == 'scheduled')
                    this.publishAt = this.dateTimePicker
            }
        },
        computed: {
            contentData() {
                return this.$store.getters.contentData
            },
            publishedAt() {
                return this.$store.getters.publishedAt
            },
            editorMode() {
                return this.$store.getters.editorMode
            },
            containerList: {
                get() {
                    return this.$store.getters.rootItems
                },
                set(object) {
                    // console.log('set order for blocks', object)
                    this.updateItemsList({list: _.map(object, 'uniqueId')})
                }
            },
            saveBtnText: function() {
                if(this.saveBlocks)
                    return 'Saving'
                else {
                    return 'Save'
                }
            },
            statusMode: function() {
                let publishedStatus = 'publish'

                if(!this.saved && this.status == 1)
                    publishedStatus = 'publish'
                else if(!this.saved && this.status == 2)
                    publishedStatus = 'draft'
                else if(!this.saved && this.status == 3)
                    publishedStatus = 'schedule'

                if(!this.saved && this.status == 1 && this.dbStatus == 1)
                    publishedStatus = 'published'

                else if(!this.saved && this.status == 3 && this.dbStatus == 3)
                    publishedStatus = 'scheduled'

                if(this.saved && this.status == 1)
                    publishedStatus = 'published'
                else if(this.saved && this.status == 2)
                    publishedStatus = 'draft'
                else if(this.saved && this.status == 3)
                    publishedStatus = 'scheduled'

                this.saved = false
                return publishedStatus
            },
            publishAt: {
                get() {
                    return this.$store.getters.publishAt
                },
                set(date) {
                    console.log('publishAt: '+ date)
                    let payload = new Object()
                    payload.publishAt = date
                    this.setContentData(payload)
                }
            },
            modeText: function() {
                if(this.editorMode == 'edit')
                    return 'Edit'
                else
                    return 'Create'
            },
            statusText: function () {
                let text = ''

                if(this.statusMode == 'publish')
                    text =  'Publish'
                else if(this.statusMode == 'draft')
                    text = 'Draft'
                else if(this.statusMode == 'schedule')
                    text = 'Schedule'

                if(this.statusMode == 'published')
                    text = 'Published'
                else if(this.statusMode == 'scheduled')
                    text = 'Scheduled'

                return text

            },
            dateText: function () {
                let dateText
                if(this.status == 1)
                    dateText = 'Immediately'
                else if(this.status == 2)
                    dateText = 'Not yet'

                if(this.editorMode == 'edit' && this.status == 1 && this.dbStatus == 1)
                    dateText = this.publishedAt
                else if(this.editorMode == 'edit' && this.status == 1 && this.dbStatus == 3)
                    dateText = 'Immediately'

                return dateText
            }
        },
        methods: {
            ...mapActions([
                'addItem',
                'removeItem',
                'setEditorMode',
                'setTemplateSlug',
                'setContentData',
                'updateItemsList',
                'fetchContentBlocks'
            ]),
            addContainer(compName = undefined) {
                let comp = getComponentByName(compName)
                if (!comp) {
                    alert('Wrong component\'s name')
                    return false
                }

                let customSettings = processSettingsConfig(compName)

                this.addItem({
                    type: compName,
                    title: 'Container',
                    settingsConfig: customSettings,
                    settings: _.mapValues(customSettings, object => (object.default === undefined)? null : object.default)
                })
            },
            removeFeaturedImage() {
                let formData = {
                    id: this.contentId
                }
                return axios.post(route('backend.content.remove.featuredimage'), formData)
                    .then((response) => {
                        this.featuredImage = null
                    })
                    .catch((error) => {
                        console.log(error)
                    })

            },
            setFeaturedImage(image) {
                this.featuredImage = image
                let formData = {
                    id: this.contentId,
                    featuredImageId: this.featuredImage.id
                }
                return axios.post(route('backend.content.set.featuredimage'), formData)
                    .then((response) => {
                        console.log('featured image saved')
                    })
                    .catch((error) => {
                        console.log(error)
                    })

            },
            openMediaModal() {
                var mode = 'featuredImage'
                var params = new Object

                params.cb = (image) => {
                    this.setFeaturedImage(image)
                }

                this.$bus.$emit('open-media-modal', mode, params)
            },
            onEnd(evt) {
            },
            onMove(evt) {
                return !evt.related.classList.contains('item_disabled')
            },
            localDateTime(dateTime) {
                if(dateTime)
                    return moment.utc(dateTime, 'YYYY-MM-DD HH:mm').local().format('YYYY-MM-DD HH:mm')
                else {
                    return null
                }
            },
            saveBtn() {
                this.$validator.validateAll().then( result => {
                    if (result) {
                        this.save()
                    }
                })
            },
            save () {
                this.$store.dispatch('saveAll')
            },
            cycleStatus() {
                this.status = this.status + 1
                if(this.status > 3)
                    this.status = 1
            },
            removeContainer(containerId) {
                this.removeItem({
                    id: containerId
                })
            },
            stringToBoolean: function(string) {
                switch(string.toLowerCase().trim()){
                    case "true": case "yes": case "1": return true;
                    case "false": case "no": case "0": case null: return false;
                    default: return Boolean(string);
                }
            },
        },
        mounted: function() {
            let self = this

            if(this.initEditorMode == 'create') {
                this.setEditorMode('create')
                let payload = {
                    contentTypeSlug: this.contentType,
                    contentTypeId: this.initContentTypeId,
                }
                this.setContentData(payload)
                this.fetchContentBlocks({mode: 'default'})
            } else if(this.initEditorMode == 'edit') {
                this.setEditorMode('edit')
                let payload = {
                    contentId: this.initContentId,
                    contentTitle: this.initContentTitle,
                    contentTypeSlug: this.initContentType,
                    contentTypeId: this.initContentTypeId,
                    publishedAt: this.localDateTime(this.initPublishedAtDate),
                    createdAt: this.localDateTime(this.initCreatedAtDate),
                    updatedAt: this.localDateTime(this.initUpdatedAtDate),
                }
                this.setContentData(payload)
                this.fetchContentBlocks({contentId: this.initContentId})
            }

            window.addEventListener("popstate", function(e) {
                var path = location.pathname
                path = path.replace(/create\b/g, "")
                window.location = window.location.protocol + "//" + window.location.host + path
            })

            window.addEventListener('keydown', function(event) {
                let key = event.keyCode

                if(event.ctrlKey) {
                    switch (key) {
                        // char M pressed - minimal layout
                        case 77:
                            event.preventDefault()
                            self.minimalLayout = !self.minimalLayout

                            var formData = {
                                minimalLayout: {type: 'boolean', value: self.minimalLayout}
                            }

                            axios.post(route('backend.content.settings.save'), formData)
                        break;

                        // char L pressed - wide layout
                        case 76:
                            event.preventDefault()
                            self.wideLayout = !self.wideLayout
                            var formData = {
                                contentTypeId: self.initContentTypeId,
                                settings: {
                                    wideLayout: {type: 'boolean', value: self.wideLayout}
                                }
                            }

                            axios.post(route('backend.content.settings.save'), formData)
                        break;

                        // char H pressed
                        case 72:
                            event.preventDefault()
                            let shouldWeShowHeaders = !self.showHeaders

                            if(!self.showContent)
                                shouldWeShowHeaders = true

                            self.showHeaders = shouldWeShowHeaders
                        break;

                        // char G pressed
                        case 71:
                            // console.log('hide content')
                            event.preventDefault()

                            let shouldWeShowContent = !self.showContent

                            if(!self.showHeaders)
                                shouldWeShowContent = true

                            self.showContent = shouldWeShowContent
                            console.log('showContent: ' + self.showContent)
                        break;
                    }
                }
            })
        },
    }
</script>

<style lang="less" scoped>

    .featured-image {
        cursor: pointer;
    }

    .set-featured-image {
        text-align: center;
        border: 1px dashed rgba(0, 0, 0, 0.19);
        padding: 35px;
        cursor: pointer;
        font-size: 16px;
    }

    .remove-featured-image {
        cursor: pointer;
        margin-top: 5px;
        padding: 10px;
        font-size: 15px;
        background-color: rgb(44, 107, 143);
        color: white;
    }

    .btn-primary {
        background-color: rgba(87, 113, 128, 0.09);
        border-color: rgba(54, 127, 169, 0);
    }

    .btn-primary:hover, .btn-primary:active, .btn-primary.hover {
        background-color: rgba(103, 137, 157, 0.19);
    }

    .btn-primary:hover {
        color: #fff;
        background-color: rgba(40, 96, 144, 0.42);
        border-color: rgba(32, 77, 116, 0.17);
    }

    .mydiv {
        width: 200px;
        margin-right: 20px;
        float: left;
    }
</style>

<style>
    .fa-arrows {
        cursor: move;
        font-size: 16px;
        margin-right: 8px;
    }

    .fa-cog, .fa-eye, .fa-eye-slash, .fa-caret-square-o-down, .fa-times, .fa-arrow-circle-o-down, .fa-arrow-circle-o-up {
        cursor: pointer;
        font-size: 16px;
        margin-right: 8px;
        color: #b8c7ce !important;
    }

    .content-block {
        margin-bottom: 15px;
    }

    .content-block-header {
        padding: 10px;
        background: rgba(0,0,0, 0.1)
    }
</style>
